import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#B8E9F5', fontFamily: 'Pretendard-Medium' },
  loadingOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.3)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 60,
    paddingBottom: 20,
  },
  backButton: { padding: 4 },
  headerTitle: { fontWeight: '600', color: '#000', paddingLeft: 140, paddingRight: 90 },
  logoutButton: { color: '#02BFDC' },
  content: { flex: 1, paddingHorizontal: 30 },
  profileImageContainer: { alignItems: 'center', marginBottom: 30, marginTop: 20 },
  profileImageWrapper: {
    width: 120,
    height: 120,
    borderRadius: 20,
    backgroundColor: '#FFB8B8',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  profileImage: { width: '90%', height: '90%', resizeMode: 'contain', marginTop: 13 },
  profileName: { fontWeight: '600', color: '#000' },
  section: { backgroundColor: '#fff', borderRadius: 16, padding: 20, marginBottom: 16 },
  sectionTitle: { fontWeight: '600', color: '#000', marginBottom: 16 },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  menuLabel: { color: '#000' },
  menuValue: { color: '#666' },
  menuRight: { flexDirection: 'row', alignItems: 'center', gap: 4 },
  menuLink: { color: '#02BFDC' },
  fontSizeMenu: { marginTop: 8, backgroundColor: '#F8F8F8', borderRadius: 12, padding: 8 },
  fontSizeOption: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  fontSizeLabel: { color: '#000' },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modalContent: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 24,
    width: '100%',
    maxWidth: 400,
  },
  modalTitle: { fontWeight: '600', color: '#000', marginBottom: 20, textAlign: 'center' },
  modalInput: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    marginBottom: 20,
  },
  modalButtons: { flexDirection: 'row', gap: 12 },
  modalButton: { flex: 1, paddingVertical: 14, borderRadius: 12, alignItems: 'center' },
  modalButtonCancel: { backgroundColor: '#F0F0F0' },
  modalButtonConfirm: { backgroundColor: '#02BFDC' },
  modalButtonTextCancel: { color: '#666', fontWeight: '600' },
  modalButtonTextConfirm: { color: '#fff', fontWeight: '600' },
});